### PR TITLE
fix definition lists

### LINKED ISSUE #86: Definition lists don't work
With the switch to vitepress, we lost the ability to use the [definition list syntax](https://github.com/markdown-it/markdown-it-deflist) as it's also shown in the [demo page](https://markdown-it.github.io/). I tried explicitly importing and adding it to the config, but it had no effect.

### PR DESCRIPTION
**Pull request by TerminalFi**
Config was formatted incorrectly. Bumped vitepress at the same time

fixes #86

### CODE REVIEW

File: docs/.vitepress/utils/term-parser.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  // Currently duplicating to fix a where bug.
+  // Without this :override_package: is not detect
+  // http://localhost:5173/guide/extensibility/packages.html#merging-and-order-of-precedence
+  {
+    regex: /:([\w+]*):/g,
+    modifier: (match: RegExpMatchArray) => {
+      const m1 = match[1].replace(/_/g, " ");
+      return `<Term term="${m1}"/>`;
+    },
+  },
```
Comment (TerminalFi) [inline docs/.vitepress/utils/term-parser.ts:31]: Not happy with this. Also no clue what is going on that requires this in order for all terms to be captured. Would love some additional eyes here

File: docs/.vitepress/config.ts [hunk 2]
```diff
@@ -172,15 +175,18 @@ export default defineConfig({
...
-      toc: {
-        level: [2]
+  },
+  markdown: {
+    theme: 'material-theme-palenight',
+    lineNumbers: true,
+    config: md => {
+      md.use(markdownItDeflist);
+      for (const pattern of patterns) {
+        md.use(markdownItRegexp(pattern.regex, pattern.modifier));
```
Comment (FichteFoll) [inline docs/.vitepress/config.ts:185]: I'd rather we used the same method of extending the markdown from a plugin like before, i.e. define an `extendMarkdown` function in term-parser that we call here so that the config.ts doesn't need to know in detail what term-parser does.

File: docs/.vitepress/components/Glossary.vue [hunk 3]
```diff
@@ -0,0 +1,43 @@
+<!-- Taken and modified from https://gitlab.com/eeriksp/vuepress-plugin-glossary -->
```
Comment (FichteFoll) [inline docs/.vitepress/components/Glossary.vue:1]: Why exactly did we need to modify it? What about the licence?

File: docs/.vitepress/data/glossary.data.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
+export default {
+  load() {
+    return {
+      "buffer": "Data of a loaded file and additional metadata, associated with one or more views. The distinction between buffer and :view: is technical. Most of the time, both terms can be used interchangeably.",
```
Comment (FichteFoll) [inline docs/.vitepress/data/glossary.data.ts:4]: I preferred the YAML frontmatter over this JS dict, but i assume we need this as a data file to be able to check for a term's existence?

File: docs/.vitepress/utils/term-parser.ts [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+  {
+    regex: /:([\w+]*):([\w+]*):/g,
+    modifier: (match: RegExpMatchArray) => {
+      console.log(match)
+      const m1 = match[1].replace(/_/g, " ");
+      const m2 = match[2].replace(/_/g, " ");
+      return `<Term term="${m1}" show="${m2}"/>`;
+    },
+  },
+  // Currently duplicating to fix a where bug.
```
Comment (FichteFoll) [inline docs/.vitepress/utils/term-parser.ts:11]: To fix a what?

Either way, when we have our own `Term` tag, we can use that directly in the future instead of doing string replacements, which is less magical and wouldn't require these parsing rules. Then we also don't need to worry about this weird bug.

Of course, parsing is fine for the moment until all references are migrated, but I'd like to mention somewhere that this is only temporary.

File: docs/.vitepress/components/Term.vue [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+
+const definition = computed(() => {
+  const termWithSpaces = replaceUnderscoresWithSpaces(props.term);
+  const termDefinition = data[termWithSpaces];
+
+  if (termDefinition) {
+    return removeTermLink(termDefinition);
+  }
+
+  termNotFound.value = true;
```
Comment (FichteFoll) [inline docs/.vitepress/components/Term.vue:29]: `computed` props should not have side effects. We'll want an additional `termText` property than the `termNotFound` boolean is derived from.

**Review by FichteFoll — COMMENTED** [review]
Thanks for working on this. I have a few ideas on how to tackle my comments but I'd like you to answer some of my questions first before I begin diving into it myself.

File: docs/.vitepress/data/glossary.data.ts (hunk 4 above)
Comment (TerminalFi) [reply docs/.vitepress/data/glossary.data.ts:4]: Yaml frontmatter isn’t accessible from another page with vitepress like it was with Vuepress. Not in a documented way.

Comment (TerminalFi) [reply docs/.vitepress/data/glossary.data.ts:4]: Yes, because vitepress does not have a documented way for other pages to access another pages frontmatter

File: docs/.vitepress/components/Glossary.vue (hunk 3 above)
Comment (TerminalFi) [reply docs/.vitepress/components/Glossary.vue:1]: Removed props, which I guess we could restore and then pass the data still. Simplified

File: docs/.vitepress/config.ts (hunk 2 above)
Comment (TerminalFi) [reply docs/.vitepress/config.ts:185]: Yeah, probably best.

File: docs/.vitepress/utils/term-parser.ts (hunk 5 above)
Comment (TerminalFi) [reply docs/.vitepress/utils/term-parser.ts:11]: Remove the duplicated instance and it will show clearly the bug. For some reason, it seems to skip over some instances. The pageI put in the comment will show this clearly. 

However, I guess replacing these string replacements with our own component would fix it anyway.

**Comment by FichteFoll** [comment]
I have revised the code here and pushed onto the branch. Looks good from my side now. PTAL.

**Comment by TerminalFi** [comment]
Looks good to me

File: docs/.vitepress/config.ts [hunk 7]
```diff
@@ -19,10 +21,10 @@ export default defineConfig({
   title: 'Sublime Text Community Documentation',
   description: 'Community-driven Documentation for Sublime Text',
   head: customHead,
+  appearance: 'dark',
```
[the remark this answers is not in the document]
Comment (TerminalFi) [reply docs/.vitepress/config.ts:24]: Unless something is wrong. These things did not through an error. I caught it by going through the config by hand.

[the remark this answers is not in the document]
Comment (FichteFoll) [reply docs/.vitepress/config.ts]: I almost did that today, but ended up not doing it today because I haven't fully committed my LSP configuration of another machine to my dotfiles repo yet and didn't want to reconfigure everything from scratch.

(I hope LSP-vue works with vitepress …)

**Comment by FichteFoll** [comment]
I noticed I forgot to commit 4 files, so I force-pushed them. And made a few more changes on top. Merging this to deploy it.
